# Home Assistant Test Environment with Real Electricity Price Integration
#
# This setup provides a complete development environment with:
# - Home Assistant running in Podman (discrete as "dc")
# - Nginx reverse proxy for maximum network discretion
# - Integration files automatically synced
# - HACS pre-installed for integration testing
# - Development-friendly configuration
#
# Usage: podman-compose up -d

services:
  homeassistant:
    container_name: dc
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # Home Assistant configuration
      - ./container/config:/config
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/Tallinn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "dev.project=real-electricity-price"
      - "dev.environment=development"
    networks:
      - internal

networks:
  internal:
    driver: bridge
