# Services for Real Electricity Price integration

refresh_data:
  name: Refresh Data
  description: Manually refresh electricity price data from Nord Pool API
  fields: {}

recalculate_cheap_prices:
  name: Recalculate Cheap Prices
  description: Manually recalculate cheap price periods based on current configuration
  fields: {}
