name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  basic-tests:
    name: Basic Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/test-requirements.txt

      - name: Run syntax checks
        run: |
          cd tests
          ./test.sh syntax
        continue-on-error: false

      - name: Run import tests  
        run: |
          cd tests
          ./test.sh import
        continue-on-error: false

      - name: Run configuration validation
        run: |
          cd tests
          ./test.sh config
        continue-on-error: false

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [basic-tests]
    if: always()
    
    steps:
      - name: Test Results Summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Basic Integration Tests: ${{ needs.basic-tests.result }}" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ needs.basic-tests.result }}" == "success" ]]; then
            echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
            exit 0
          else
            echo "❌ Some tests failed!" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
